/*
 * CREATE EVENT_STUDENT
 */

 CREATE TABLE EVENT_STUDENT(
	EventID		INT						NOT NULL,
	StudentID	INT						NOT NULL,

	CONSTRAINT	PK_EventStudent			PRIMARY KEY (EventID, StudentID),
	
	CONSTRAINT	FK_EventStudent_Event	FOREIGN KEY (EventID)				REFERENCES	SPECIAL_EVENT	(EventID)
		ON DELETE	NO ACTION
		ON UPDATE	NO ACTION,

	CONSTRAINT	FK_EventStudent_Student	FOREIGN KEY (StudentID)				REFERENCES	STUDENT	(StudentID)
		ON DELETE	CASCADE
		ON UPDATE	CASCADE
	);