/*
 * CREATE USER
 */

CREATE TABLE [USER] (
	UserID		INT				NOT NULL	IDENTITY(1000,1)	PRIMARY KEY,
	[Password]	VARCHAR(40)		NOT NULL,
	UserTypeID	INT				FOREIGN KEY	REFERENCES	USER_TYPE(UserTypeID)
	);