/*
 * CREATE USER
 */

CREATE TABLE [USER] (
	UserID		INT				NOT NULL	IDENTITY(1000,1)	PRIMARY KEY,
	[Password]	VARCHAR(40)		NOT NULL,
	UserTypeID	INT,
	
	CONSTRAINT FK_User_Type	FOREIGN KEY	(UserTypeID)	REFERENCES	USER_TYPE(UserTypeID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
	);